import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from "../components/Header"
import TopCard from '@/components/TopCard'
import BarChart from '@/components/BarChart'
import RecentOrders from '@/components/RecentOrders'
import { Grid } from '@mui/material'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
   
   <TopCard/>
   <Grid container spacing={4}>
    <Grid item><BarChart/></Grid> 
    <Grid item> <RecentOrders/></Grid>
    
   
    </Grid>
      </main>
    </>
  )
}
